name: Update Overwatch Map Vote Data

on:
  # schedule:
  #   - cron: "0 3 * * *"  # Every day at 3:00 AM UTC
  workflow_dispatch:     # Manual trigger option

jobs:
  update-vote-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # Keep GitHub credentials for push

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run update script
        run: python app.py

      - name: Push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add vote_data_whitelisted.csv
          git commit -m "Automated update" || echo "No changes to commit"
          git push
