name: Update CSV Data Manually

on:
  workflow_dispatch:
    inputs:
      debug:
        description: "Enable debug mode"
        required: false
        default: "false"
      whitelist:
        description: "Run on whitelist"
        required: false
        default: "true"
      start_date:
        description: "Start date (YYYY-MM-DD)"
        required: false
        default: "2025-06-24"
      end_date:
        description: "End date (YYYY-MM-DD)"
        required: false
        default: "2025-06-26"
      vods_limit:
        description: "Max number of VODs to process"
        required: false
        default: "100"

jobs:
  update-vote-data:
    runs-on: ubuntu-latest

    env:
      TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}
      TWITCH_SECRET: ${{ secrets.TWITCH_SECRET }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # For pushing changes

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # Keep GitHub credentials for push

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run update script
        run: |
          python app.py \
            --debug=${{ github.event.inputs.debug }} \
            --whitelist=${{ github.event.inputs.whitelist }} \
            --start-date=${{ github.event.inputs.start_date }} \
            --end-date=${{ github.event.inputs.end_date }} \
            --vods-limit=${{ github.event.inputs.vods_limit }}

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
          git add *.csv
          git commit -m "Automated update" || echo "No changes to commit"
          git push
